import type { Metadata } from "next";
import "./globals.css";
import { StyledEngineProvider } from "@mui/material";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StyledEngineProvider injectFirst>

            <html lang="en">
            <body
                className={` antialiased mx-24`}
            >
            {children}
            </body>
            </html>
        </StyledEngineProvider>
    );
}
